Controllers films users
Cavacubo/java-filmorate pull request #1
Opened 2023-02-09 22:35 UTC by Cavacubo

2023-02-11 03:01 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-02-11 03:01 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +           throw new ValidationException("id does not exist: " + user.getId());
А в этом случае исключение должно быть другим!
Тут мы должны ответить клиенту кодом 404 Not found поэтому и нужно завести еще одни класс: NotFoundException и использовать его тут!

2023-02-13 20:17 UTC, Cavacubo commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Денис, привет! 
Это мой первый полноценный PR! Спасибо большое, мне очень приятно!:)

2023-02-13 20:18 UTC, Cavacubo commented on pom.xml
> +	<version>0.0.1-SNAPSHOT</version>
Спасибо,  очень интересно было почитать про семантическое версионирование, много нового для себя узнала! Исходя из полученных знаний, проставила версию.

2023-02-13 20:18 UTC, Cavacubo commented on .gitignore
> +../target/
Это мой баг,  поправила, спасибо.

2023-02-13 20:19 UTC, Cavacubo commented on src/main/resources/application.properties
> +logging.level.ru.yandex.practicum.catsgram.controller=debug
Исправила. Закомментировала код из задания в файле.
Дублирую здесь решение:
server:
#  port: 0
Интересно было попробовать yaml

2023-02-13 20:20 UTC, Cavacubo commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Collection<Film> findAll() {
Готово

2023-02-13 20:21 UTC, Cavacubo commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("id does not exist: " + film.getId());
Согласна, я бы использовала такие исключения. 
Изначально я следовала ТЗ, где предлагалось так сделать.

2023-02-13 20:22 UTC, Cavacubo commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +           throw new ValidationException("id does not exist: " + user.getId());
Готово!

2023-02-14 17:39 UTC, FanaticFiz approved these changes

2023-02-14 23:30 UTC, merged