Add friends likes
Cavacubo/java-filmorate pull request #2
Opened 2023-03-05 12:40 UTC by Cavacubo

2023-03-05 19:42 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-03-05 19:42 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleIncorrectParameterException(final IncorrectParameterException exception) {
Ты используешь этот эксепшн, вот так:

```
if (userId < 0) {
    throw new IncorrectParameterException("userId");
}
```

Почему тогда это ответ HttpStatus.NOT_FOUND ?
Это должен быть BAD_REQUEST.

Но! Для него у тебя уже есть класс: `BadRequestException` !!!

Т.е. `IncorrectParameterException` вообще лишний класс. Его везде вледует заменить на BadRequestException

2023-03-05 19:42 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ErrorResponse(exception.getMessage());
Не плохо было бы логировать тут ошибки

2023-03-05 19:42 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Current number of films: {}", filmService.findAllFilms().size());
Ну вот.... и в логере вызвали и потом уже по делу вызвали метод `filmService.findAllFilms()`.
Когда будет БД - это вызовет два запроса.
Объяви переменную!

2023-03-05 19:42 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          log.debug("Film: {} updated", film.getName());
`film.getName()` до проверки фильма. Это вызовет NullPointerException

2023-03-05 19:42 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private void validate(Film film) {
Валидация напрасно переехала в сервис, это работа контроллера.

2023-03-05 19:42 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.findAll().stream()
Поскольку у нас есть хранилище, то в нем должен быть метод getPopularFilms

2023-03-05 19:42 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    Film getFilmById(int id);
Используй `Optional` и давай в хранилищах использовать глагол `find` а в сервисах `get`

`Optional<Film> findById(int id);`

2023-03-05 19:42 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            throw new NotFoundException("Film with id: " + id + " is not found");
Хранилище только достает и возвращает сущности, что делать если сущности нет надо решать в сервисе.
Подобные ексепшены нужно бросать из сервиса...

2023-03-09 14:56 UTC, Cavacubo commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleIncorrectParameterException(final IncorrectParameterException exception) {
Денис, привет! Спасибо за комментарии. Я удалила этот класс IncorrectParameterException.  Сначала сделала все так, как ты пишешь, но у меня проходили тесты в Postman, там ожидался другой тип, 404 вместо 400, поэтому я поменяла на NotFoundException. 
<img width="805" alt="image" src="https://user-images.githubusercontent.com/24245222/224062557-2aa005db-357b-4881-9e66-eec105b3a498.png">
P.S.: Надеюсь, скрин не прошедших тестов загрузился.

2023-03-09 18:06 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-03-09 18:06 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleIncorrectParameterException(final IncorrectParameterException exception) {
Всё правильно сделала )

2023-03-09 18:06 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            throw new NotFoundException("id does not exist: " + film.getId());
Как же так! 
Мы только что исправили это и вынесли подобные эксепшены из хранилища в сервис...

И тут же в другом месте эту же ошибку делаешь! 

"Подобные ексепшены нужно бросать из сервиса..."

2023-03-09 18:06 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +import ru.yandex.practicum.filmorate.exception.NotFoundException;
Из хранилища `NotFoundException` не бросается...

2023-03-10 18:00 UTC, Cavacubo commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        log.error("BAD_REQUEST: " + exception.getMessage());
Да, спасибо. Забыла

2023-03-10 18:05 UTC, Cavacubo commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +import ru.yandex.practicum.filmorate.exception.NotFoundException;
Поправила

2023-03-11 15:43 UTC, FanaticFiz approved these changes

2023-03-12 07:38 UTC, merged